### ISSUE TITLE
[J-TB] 모집 글쓰기 페이지 

### ISSUE THREAD

**Issue by SaltySalt77** [peer-42seoul/Peer-Frontend#546]
##### 기능적 문제
1. 역할 설정하는 부분에서 글자 수 제한이 걸려있지 않습니다.
2. 역할 삭제가 불가능합니다. 
##### 디자인 적 문제
1. PC에서 컨테이너의 사이즈 px로 지정이 되어있어 가로 화면이 좁으면 등록버튼이 안보입니다.
2. 타이포그래피의 variant가 디자이너님이 지정해주신 폰트 위계에 맞지 않는 mui 기본 variant로 지정이 되어있습니다.
3. 색상 지정이 헥사코드 또는 색상 이름으로 되어있어 라이트/다크모드 적용이 안되는 있는 부분이 있습니다.
4. 아이콘이 디자이너님이 만들어주신 아이콘이 아닌 mui의 아이콘으로 적용이 되어있습니다. 

#### 테스트 환경

- OS(mac / ipad / android...) : 관련 없음
- 웹 브라우저 : 관련 없음

#### 사전 조건 (ex. 로그인 여부)
모집글 쓰기 페이지에서 프로젝트를 선택합니다.

#### 재현 절차
(생략)

#### 예상 결과
(생략)

#### 실제 결과
(생략)

#### 심각도
중

**Comment by SaltySalt77** [comment]
### ToDo
- [ ] 역할 설정하는 부분에서 글자 수 제한
- [ ] 역할 삭제가 불가능 버그 수정
- [ ] 레이아웃 단위 변경
- [ ] 타이포그래피의 variant로 재 지정
- [ ] 색상 지정 재 지정

**Comment by SaltySalt77** [comment]
### 리엑트 훅 폼 등록 리스트 (필수 값만 넣기)
- [ ] 이미지
- [ ] 유형
- [ ] 제목
- [ ] 팀명
- [ ] 역할
- [ ] 기간
- [ ] 지역
- [ ] 소통 링크
- [ ] 기술 스택
- [ ] 설명 (이건 나중에 토스트 에디터 연결하기)

**Comment by SaltySalt77** [comment]
인터뷰까지 모두 리액트 훅 폼과 연결했으므로 이슈 닫습니다~
